### ISSUE TITLE
[ATO] Research and implement new vulnerability tracking tool 

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#2996]
Gemnasium will be shutdown on May 15th. We need to use another tool. This tool, Snyk, was suggested by @LindsayYoung https://snyk.io/. We want to test out a new vulnerability tracking tool before Gemnasium expires. We can hook up both Gemnasium and Snyk at the same time to test it out and when we are ready, we can remove Gemnasium. 

CMS first as a test.

Completion Criteria:
- [x]  Check with security to make sure this tool is approved for use
- [x] Research and document Snyk's capabilities
- [x] Hook up Snyk to one FEC repo to try it out
- [x] Add badge to the to the FEC repo to test it
- [x] Share the results of the testing and research

**Comment by patphongs** [comment]
I am currently on step 1, which is to check with security to make sure this tool is approved for use. This requires us to assess the product through our fedramp low tailored approach. I'll pair with @JayRibeiro more to see what is fully needed with this. Until we get approval to use this, we'll have to hold off on any further implementation.

**Comment by patphongs** [comment]
@JayRibeiro Has given us the green light to test out SNYK. This is no longer blocked and can move forward

**Comment by patphongs** [comment]
I have implemented this tool on 4 of our github code repos:
- fec-cms
- openFEC
- fec-eregs
- fec-pattern-library

Initial findings have been very positive. Documentation for the tool is clean and simple to use. Documentation can be found here: https://snyk.io/docs/using-snyk/#wizard

**Positive findings:**
- Free for open source github repos
- Includes dependency trees where you can see all the dependencies of a dependency
- Wizards to update versions for you locally to try out. Note this is only for node dependencies though, we'd need to remediate python manually.
- A SNYK config file to remember what you’ve already tried to remediate or ignore

**Comment by patphongs** [comment]
All the items here are complete and will be shared during sprint demo on Monday. Will close this ticket after demo on Monday.

**Comment by patphongs** [comment]
Closing this ticket now. We have a separate [issue](https://github.com/fecgov/openFEC/issues/3031 ) where we will check the logs to fully test in sprint 5.5 to compare the snyk vs gemnasium alerts.
