### ISSUE TITLE
Add name to ofec_pacronyms

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#4210]
**What we are after**:
We would like users to find candidates by their commonly know name.

**Task**
Add Klobuchar as a pacronym of Amy for America

pacronym: KLOBUCHAR
id number: C00696419
full name: AMY FOR AMERICA
city: MINNEAPOLIS
state: MN
connected organization or sponsor name: [NULL]
designation: PRINCIPAL CAMPAIGN COMMITTEE
committee type: PRESIDENTIAL

**Completion criteria**
- [x] Add Klobuchar as a pacronym of Amy for America
- [x] Wait for MV refresh
- [x] Confirm that searching "Klobuchar" on sitewide search brings up Amy for America

**Comment by lbeaufort** [comment]
@PaulClark2 should the designation be **PRINCIPAL** CAMPAIGN COMMITTEE?

**Comment by lbeaufort** [comment]
@fecjjeng here's my insert statement - my only fuzzy bit is how to generate the `index` column value. I'm also waiting for Paul on my question above.

```
INSERT INTO ofec_pacronyms 
VALUES (
    DEFAULT, -- TODO: How does this get populated?
    'KLOBUCHAR',
    'C00696419',
    'AMY FOR AMERICA',
    'MINNEAPOLIS',
    'MN',
    NULL,
    'PRINCIPAL CAMPAIGN COMMITTEE',
    'PRESIDENTIAL TYPE'
);
```

**Comment by fecjjeng** [comment]
@lbeaufort The "index" column of this particular table is manually created.   
If this is a table that is frequently inserted/updated by script, I would set up a default value for it  to be automatically populated by a sequence, or use a trigger.

**Comment by PaulClark2** [comment]
@lbeaufort @fecjjeng should we be more encompassing? When we add committees to pacronyms does is change how the search rank orders them? 

These candidate committees with financial activity do not contain the candidate's last name. The query below is for 1979 through 2024. If we are adding more, we could limit it to 2019 through 2024. 

```
select distinct cn.fec_election_yr, cn.cand_election_yr, cn.cand_id, cn.cand_name, cn.cand_ici, cn.cand_status, cn.cand_office_st, cn.cand_office, cn.cand_office_district, cm.cmte_id, cm.cmte_nm, cm.cmte_tp, cm.cmte_dsgn
from DISCLOSURE.CAND_CMTE_LINKAGE ccl, DISCLOSURE.committee_summary cm, DISCLOSURE.CAND_VALID_FEC_YR cn
where ccl.cmte_id = cm.cmte_id
and ccl.cand_id = cn.cand_id
and ccl.fec_election_yr = ccl.cand_election_yr
and cn.fec_election_yr = cn.cand_election_yr
and cm.fec_election_yr = cn.fec_election_yr
and CN.CAND_ELECTION_YR between 1979 and 2024
and substr(ccl.cand_id,1,1) = ccl.cmte_tp
and cm.cmte_tp in ('H', 'S', 'P')
and substr(ccl.cand_id,1,1) = ccl.cmte_tp
and ccl.cmte_dsgn in ('P', 'A')
and cm.cmte_nm not like '%'||NVL(SUBSTR(cn.cand_name, 0, INSTR(cn.cand_name, ',')-1), cn.cand_name)||'%'
and CM.TTL_RECEIPTS+CM.TTL_DISB+CM.COH_COP+CM.DEBTS_OWED_BY_CMTE >0;
```

**Comment by PaulClark2** [comment]
@lbeaufort the second to last line of your insert script should probably be `'PRESIDENTIAL'` instead of `'PRESIDENTIAL TYPE'`

**Comment by lbeaufort** [comment]
@PaulClark2 I’m fine being more encompassing. Results are ordered by financial activity, so additions won’t change sort order except inserting more values.

**Comment by PaulClark2** [comment]
@lbeaufort thanks. Let's insert them all from 1979 through 2024.

**Comment by PaulClark2** [comment]
@lbeaufort you might want to refine my script. I noticed two examples where it incorrectly includes a committee even though the last name is part of the committee name.  It might also be just as quick to scan the list instead of refining the script. There are only 800-or-so of these. cc: @fecjjeng  

P00014357 BUCHSER-LOCHOCKI, SUSAN C00728014 FRIENDS OF SUSAN BUCHSER LOCHOCKI FOR PRESIDENT OF THE USA

H8AL02130 BRIGHT SR, BOBBY NEAL C00446138 BRIGHT FOR CONGRESS

**Comment by fecjjeng** [comment]
@lbeaufort the following row had been inserted into DEV.  Please review it and let me know if we want to insert into STG and PRD.  
INSERT INTO ofec_pacronyms 
(index,
  "PACRONYM",
  "ID NUMBER",
  "FULL NAME",
  "CITY",
  "STATE",
  "CONNECTED ORGANIZATION OR SPONSOR NAME",
  "DESIGNATION",
  "COMMITTEE TYPE"
  )
VALUES (
    1486,
    'KLOBUCHAR',
    'C00696419',
    'AMY FOR AMERICA',
    'MINNEAPOLIS',
    'MN',
    NULL,
    'PRINCIPAL CAMPAIGN COMMITTEE',
    'PRESIDENTIAL'
);

**Comment by lbeaufort** [comment]
@fecjjeng @PaulClark2 I confirmed on Dev after a MV refresh that Amy for America now appears in the committee search when you type “Klobuchar” 
![8BE557BD-95BA-4372-9145-EFB4F221AF48](https://user-images.githubusercontent.com/31420082/74964237-1b5c4400-53e1-11ea-9f01-c7a45b5bcba7.png)

**Comment by fecjjeng** [comment]
The above row for 'C00696419' had been added to ofec_pacronyms to DEV/STG/PRD.  
MATERIALIZED VIEW public.ofec_committee_fulltext_mv had been refreshed to reflect the change as well.
/*
refresh MATERIALIZED VIEW concurrently public.ofec_committee_fulltext_mv;
*/
select * from public.ofec_committee_fulltext_vw where ID = 'C00696419'; 
<img width="1145" alt="Screen Shot 2020-02-26 at 1 51 15 PM" src="https://user-images.githubusercontent.com/24943130/75377174-4510e180-589f-11ea-92d3-5943bba6b64b.png">

**Comment by fecjjeng** [comment]
@PaulClark2 @lbeaufort do you want to keep this ticket open to add more names?

**Comment by lbeaufort** [comment]
@fecjjeng I'm sorry I missed your comment. I plan to review @PaulClark2's query and make an updated insert statement today.

**Comment by lbeaufort** [comment]
I've been translating this into Postgresql but it's been taking a really long time to run, so it's been hard to get the commented out line to work. Here's what I have so far. I'll probably switch to running this on the stage database and try to figure out why it's taking so long. 

```
select distinct  POSITION(',' in cn.cand_name), cn.fec_election_yr, cn.cand_election_yr, cn.cand_id, cn.cand_name, cn.ca
 nd_ici, cn.cand_status, cn.cand_office_st, cn.cand_office, cn.cand_office_district, cm.cmte_id, cm.cmte_nm, cm.cmte_tp, cm.c
 mte_dsgn  
  from DISCLOSURE.CAND_CMTE_LINKAGE ccl, DISCLOSURE.committee_summary cm, DISCLOSURE.CAND_VALID_FEC_YR cn  
  where ccl.cmte_id = cm.cmte_id  
  and ccl.cand_id = cn.cand_id  
  and ccl.fec_election_yr::varchar = ccl.cand_election_yr::varchar  
  and cn.fec_election_yr::varchar = cn.cand_election_yr::varchar  
  and cm.fec_election_yr::varchar = cn.fec_election_yr::varchar  
  and CN.CAND_ELECTION_YR between 1979 and 2024  
  and substr(ccl.cand_id,1,1) = ccl.cmte_tp  
  and cm.cmte_tp in ('H', 'S', 'P')  
  and substr(ccl.cand_id,1,1) = ccl.cmte_tp  
  and ccl.cmte_dsgn in ('P', 'A')  
  --and cm.cmte_nm not like '%'|| COALESCE(SUBSTR(cn.cand_name, 0, (POSITION(',' in cn.cand_name) -1), cn.cand_name)||'%'  
  and CM.TTL_RECEIPTS+CM.TTL_DISB+CM.COH_COP+CM.DEBTS_OWED_BY_CMTE >0 
  LIMIT 10;   
```

**Comment by pkfec** [comment]
@lbeaufort Are you still improvising the SQL or need help with anything? could you provide an update on this issue?

**Comment by lbeaufort** [comment]
Here's the query, in psql: 

```
select distinct cn.fec_election_yr, cn.cand_election_yr, cn.cand_id, cn.cand_name, cn.cand_ici, cn.cand_status, cn.cand_office_st, cn.cand_office, cn.cand_office_district, cm.cmte_id, cm.cmte_nm, cm.cmte_tp, cm.cmte_dsgn  
  from DISCLOSURE.CAND_CMTE_LINKAGE ccl, DISCLOSURE.committee_summary cm, DISCLOSURE.CAND_VALID_FEC_YR cn  
  where ccl.cmte_id = cm.cmte_id  
  and ccl.cand_id = cn.cand_id  
  and ccl.fec_election_yr::varchar = ccl.cand_election_yr::varchar  
  and cn.fec_election_yr::varchar = cn.cand_election_yr::varchar  
  and cm.fec_election_yr::varchar = cn.fec_election_yr::varchar  
  and CN.CAND_ELECTION_YR between 1979 and 2024  
  and substr(ccl.cand_id,1,1) = ccl.cmte_tp  
  and cm.cmte_tp in ('H', 'S', 'P')  
  and substr(ccl.cand_id,1,1) = ccl.cmte_tp  
  and ccl.cmte_dsgn in ('P', 'A')  
  and cm.cmte_nm not like '%'|| COALESCE(SUBSTR(cn.cand_name, 0, (POSITION(',' in cn.cand_name))), cn.cand_name)||'%'  
  and CM.TTL_RECEIPTS+CM.TTL_DISB+CM.COH_COP+CM.DEBTS_OWED_BY_CMTE >0 
```

@fecjjeng @PaulClark2 it looks good to me - do you want to go forward with adding these to the `ofec_pacronyms` table?

**Comment by fecjjeng** [comment]
@PaulClark2 @lbeaufort 
I had created a tmp table named ofec_pacronyms_tmp in dev database.  This tmp table has all the added rows (from index 1487 and above).  Please take a look to see if that fits your need.  If it is, I will add the rows into ofec_pacronyms.

**Comment by PaulClark2** [comment]
`ofec_pacronyms_tmp` looks good to me. I did notice that a few committees have the same name and pacronym. Actblue for example. I also noticed that a few committees have single character committee types. I don't think either of these things are a big deal. 

I'm comfortable with adding these 1487 rows to pacronyms.

**Comment by fecjjeng** [comment]
[add_pacronym.txt](https://github.com/fecgov/openFEC/files/4446754/add_pacronym.txt)

/*
refresh MATERIALIZED VIEW concurrently public.ofec_committee_fulltext_mv;
*/

**Comment by fecjjeng** [comment]
@PaulClark2 @lbeaufort The above sql statements had been executed in PRD/STG/DEV database. 
MATERIALIZED VIEW public.ofec_committee_fulltext_mv had been refreshed too.
