### ISSUE TITLE
have team discussion for adding a CHANGELOG.md

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/openFEC#4504]
### Summary
We've had documentation in place for awhile outlining the steps to make a CHANGELOG.md, but we currently do not use this feature. As an experiment, I generated a changelog and submitted a PR to illustrate it.

As an example of the flexibility, I modified the default security tag to be:
`--security-labels "Security: moderate","Security: general","Security: high","Security: low"` 
and the tool generates the .md file with security issues  broken out into its own section.  Just a few examples of other enhancements:
- label for breaking changes, deprecated, removed (i.e., when a functionality is no longer  possible, it is _removed_ or _obsolete_  rather than _deprecated_)

### Completion criteria
- [ ] demo tool to team
- [ ] discuss making this file available to the public in our repo
- [ ] discuss how someone cutting the release branch can update this file and use it as a way to ask the team to update the  release notes
- [ ] discuss the possibility of using part or whole sections of CHANGELOG.md to inform release_notes.md
- [ ] open issues in other repos pending outcome of discussion

**Comment by jason-upchurch** [comment]
I'm planning to hold an ad hoc demo this sprint and will discuss with team beforehand.

**Comment by jason-upchurch** [comment]
Release notes from PI 12 Innovation sprint:
- Fix the sort by candidate and spent by columns on the elections and spending pages. [\#3904](https://github.com/fecgov/fec-cms/pull/3904) ([pkfec](https://github.com/pkfec))

for comparison, running `github_changelog_generator` on `fec-cms` and `openFEC` produces the following:

# Changelog

**Security fixes:**

- [x] update lodash v4.17.19 to fix the synk vulnerability [\#3890](https://github.com/fecgov/fec-cms/pull/3890) ([pkfec](https://github.com/pkfec))
- [x] Update wagtail to 2.7.3, exclude static directories from linting [\#3889](https://github.com/fecgov/fec-cms/pull/3889) ([lbeaufort](https://github.com/lbeaufort))


**Fixed bugs:**

- [x] Add validation for page=0 [\#4487](https://github.com/fecgov/openFEC/pull/4487) ([lbeaufort](https://github.com/lbeaufort))
- [x] Fix the broken sort by candidate\_name, committee\_name on IE, CC and EC by\_candidate endpoint [\#4482](https://github.com/fecgov/openFEC/pull/4482) ([pkfec](https://github.com/pkfec))
- [x] Update codecov pkg to v2.1.7 [\#4450](https://github.com/fecgov/openFEC/pull/4450) ([pkfec](https://github.com/pkfec))
- [x] Fix PAC and Parties total endpoints  [\#4449](https://github.com/fecgov/openFEC/pull/4449) ([hcaofec](https://github.com/hcaofec))
- [x] Fix the sort by candidate and spent by columns on the elections and spending pages. [\#3904](https://github.com/fecgov/fec-cms/pull/3904) ([pkfec](https://github.com/pkfec))

**Merged pull requests:**

- Remove unused/extra return statement for 'join\_cand\_cmte\_names' function [\#4484](https://github.com/fecgov/openFEC/pull/4484) ([lbeaufort](https://github.com/lbeaufort))
- [x]  Increase size of tres\_nm column in f\_rpt\_or\_form\_sub table [\#4470](https://github.com/fecgov/openFEC/pull/4470) ([fecjjeng](https://github.com/fecjjeng))
- [x] Update prance to address deprecation warning [\#4467](https://github.com/fecgov/openFEC/pull/4467) ([lbeaufort](https://github.com/lbeaufort))
- [x] Modernize repository language [\#4455](https://github.com/fecgov/openFEC/pull/4455) ([lbeaufort](https://github.com/lbeaufort))
- [x] Update websocket extensions [\#4454](https://github.com/fecgov/openFEC/pull/4454) ([lbeaufort](https://github.com/lbeaufort))
- [x] refine api key signup page [\#4385](https://github.com/fecgov/openFEC/pull/4385) ([jason-upchurch](https://github.com/jason-upchurch))

The codebase change not captured in release notes:
- Remove unused/extra return statement for 'join\_cand\_cmte\_names' function [\#4484](https://github.com/fecgov/openFEC/pull/4484) ([lbeaufort](https://github.com/lbeaufort))

However, the release notes include issue work by @PaulClark2  that was not picked up with `github_changelog_generator` because I excluded `issues` from the call. With "smart" labeling, we could make sure we pick up closed issues that we want to include automatically in the release notes.

Some possibilities/suggestions:

1. We could have each repo simply have a CHANGELOG.md file as standard practice. That changelog could include ALL PRs and issues, or we could decide what we want to exclude--smart use of GitHub labels will be a huge help.

2. If we want to keep our same `release_notes.md` labels in the `CHANGELOG.md` file, we can. Personally, I like calling out things like security fixes. Instead of "Merged pull requests" we could call that "under the hood" (or again, just make sure we are disciplined about labels for PRs and it will automatically go to whatever place we decide.

**Comment by jason-upchurch** [comment]
Held team discussion and demonstrated prototype changelog. Implementation of full changelog under #4679.
