### ISSUE TITLE
Test the increased API umbrella memory

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#4785]
**What we're after:**
Test the increased API umbrella memory to make sure it’s inline with what is specified in the API expires headers. 

**Possible testing scenario:** 
If there’s an amendment coming from ActBlue or WinRed, we should check the counts. Work with the DBA team to see if this adds any transaction counts from the last report. Could be a replica lag, within a few hours of the amendment being processed, the counts should match the amendment.

**Action items:**
- [x] Review implementation of [extended base cache](https://github.com/fecgov/openFEC/issues/3545). 
- [x] Hold a technical meeting about the implementation of our current schedule cache.
- [x] Verify expected behavior for API umbrella cache is following our API expires headers.
- ~~[ ] Make a new ticket if there are recommended adjustments to make for the API umbrella cache headers~~

**Completion criteria:**
- [x] Current API umbrella cache logic is documented
- [x] API umbrella cache is caching for the full time period that is specified in the API umbrella cache headers
- [ ] API umbrella cache is not serving stale data

**Comment by pkfec** [comment]
| Endpoints  	| Cache Interval 	|
|-:	|-	|
|  efile	|  	0|
|  calendar	|  	5mins|
|  legal	|  	5mins|
|  schedule A, B, C, D, E, F	|  Peak time 	|

**Comment by pkfec** [comment]
Nick from API umbrella suggested  **`curl -svo /dev/null 'URL'`** command to test request and response headers. 
I am testing **`calendar-dates`** endpoint and see how  cache works. I am documenting my finding  in a spreadsheet [Test  endpoints cache](https://docs.google.com/spreadsheets/d/1H-qoPD6S3KZOwffhj5oz53wbnj00Qv9xy9_xUuezsOY/edit#gid=1738070606)

**Comment by pkfec** [comment]
Here is the response from Nick regarding cache size and how the caching works on API umbrella:
```
Hi,
 
Sorry for not responding sooner. So I think maybe one issue that might help clear things up is that making HEAD requests (with the "curl -I" option) doesn't properly test how responses are cached (assuming you're not reliant on HEAD requests being cached). When you make a HEAD request, how the cache works is that it will return a cached response if an associated GET request for the exact same URL has been seen and cached. However, if the GET response is not cached, then the HEAD request will always be sent to the API backend and no caching will be performed. So does that perhaps explain some of these issues you were seeing when testing with curl?
 
If I instead change the tests to output headers via verbose mode, but then dump the body to /dev/null, you can better see how the cache will work. So, for example this shows caching taking place: curl -v -o /dev/null 'https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=500&calendar_category_id=36&min_start_date=2021-03-01&max_start_date=2021-04-01&_=1615393440821'
 
In terms of some of the other questions:
 
Generally speaking for the cache to work, all query string parameters (except the API key) must be identical and in the same order. If any parameters are different, then a cached response will not be given. There are also some other factors, like cookies. If a request has cookies present on it, then the cache will not be used (since cookies may indicate authenticated data that may differ between users). But if you need to exclude certain cookies from this logic to still allow caching when they're present we can configure that (eg, by default we ignore some common analytics cookies, like Google Analytics).

Caching can be defined by the server by either setting "Cache-Control" or "Expires" headers. They effectively do the same thing, just in different ways (cache-control sets a duration to be cache, while expires sets a specific time). The "Age" header is just added to the response when the server responds with any request to indicate how old the response is.
As mentioned above, not using HEAD requests with curl is probably the best way to test the cache..
Each server now has 12 GB of cache allocated.
Unfortunately, there's not really a way to see much else about the cache or expand it yourself, this is only something we can do. The cache is shared across all agencies, so while we'd certainly like to try to get this best benefiting you all, by the nature of being shared, it may be a little unpredictable, since what gets stored in the cache is determined by what items are most frequently used across all APIs. So if cached items aren't being used regularly, they may be pushed out before their expiration date to make room for other cached data. For the API request Laura originally asked about, I am seeing that being cached longer now with the increased cache size (it's currently up to ~5 hours, but still increasing). But that being said, if you're still seeing cached items not lasting as long as you'd expect on a regular basis, let us know. It's possible we could increase things further, or we may also need to try to investigate further to determine if certain agency APIs are caching very large responses and forcing other data out.
 
Sorry all of this is a bit confusing, but I hope this help! Happy to chat more about any of this.
 
Thanks,
Nick
```

**Comment by pkfec** [comment]
Nick increased the cache size to 12GB recently on each server. I tried caching SA endpoint and noticed that the SA endpoint is being cached for 9.5hours (10am-7:30pm EDT). calendar-dates endpoint is 

macadmins-mbp-5:openFEC pkasireddy$ curl -svo /dev/null 'https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00694323&two_year_transaction_period=2020&contributor_state=WV&sort=-contribution_receipt_date&per_page=30'

```
**< Date: Tue, 16 Mar 2021 22:40:58 GMT**
< Content-Type: application/json
< Content-Length: 124485
< Connection: keep-alive
< Vary: Accept-Encoding
< X-RateLimit-Limit: 40
< X-RateLimit-Remaining: 34
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
< Expect-Ct: max-age=86400
< Expires: Tue, 16 Mar 2021 23:30:00 GMT
< X-Content-Type-Options: nosniff
< X-Vcap-Request-Id: 5f15218d-b3ea-4e19-460a-022c0b2bb677
< X-Xss-Protection: 1; mode=block
< X-Frame-Options: Deny
< Strict-Transport-Security: max-age=31536000
**< Age: 30720**
< Via: http/1.1 api-umbrella (ApacheTrafficServer [cRs f ])
**< X-Cache: HIT**
```
